galerija/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, url

urlpatterns = patterns('',
	url(r'^$', 'galerija.views.main', name='main'),
	url(r'^image/(\d+)/$', 'galerija.views.image', name='image'),
	url(r'^ajax/(\d+)/$', 'galerija.views.ajax', name='ajax'),
	url(r'^ajax2/(\d+)/$', 'galerija.views.ajax2', name='ajax2'),
)

jastuk/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
	url(r'^admin/', include(admin.site.urls)),
	url(r'', include('galerija.urls')),
)

galerija/models.py
# -*- coding: utf-8 -*-

import os
from django.db import models
from PIL import Image, ImageOps
from jastuk.settings import MEDIA_ROOT
from os.path import join
from cStringIO import StringIO
from django.core.files.base import ContentFile

class Slika(models.Model):
	name = models.TextField(max_length=300, blank=True, null=True)
	image = models.FileField(upload_to="images/")
	width = models.IntegerField(blank=True, null=True)
	height = models.IntegerField(blank=True, null=True)
	ocjena = models.DecimalField(default=0.0, max_digits=5, decimal_places=2)
	thumbnail = models.ImageField(upload_to="images/", blank=True, null=True)

	def save(self, *args, **kwargs):
		super(Slika, self).save(*args, **kwargs)
		im = Image.open(join(MEDIA_ROOT, self.image.name))
		self.width, self.height = im.size

		fn, ext = os.path.splitext(self.image.name)
		thumb_fn = fn + "-thumb" + ext
		if im.mode not in ('L', 'RGB'):
			im = im.convert('RGB')
		img_type = im.format
		if img_type == 'PNG':
			DJANGO_TYPE = 'image/png'
			extension = 'png'
		elif img_type == 'GIF':
			DJANGO_TYPE = 'image/gif'
			extension = 'gif'
		else:
			DJANGO_TYPE = 'image/jpeg'
			extension = 'jpeg'
		if self.ocjena == 0:
			im = ImageOps.fit(im, (320,180), Image.ANTIALIAS)
			temp_thumb = StringIO()
			im.save(temp_thumb, extension)
			temp_thumb.seek(0)
	
			self.thumbnail.save(thumb_fn, ContentFile(temp_thumb.read()), save=False)
			temp_thumb.close()

		super(Slika, self).save(*args, **kwargs)

	def __str__(self):
		return self.image.name

	class Meta:
		verbose_name_plural = 'slike'

ocjene = [(i, i) for i in range(6)]

class Ocjene(models.Model):
	ocjena = models.IntegerField(max_length=1, choices=ocjene)
	komentar = models.TextField(max_length=300, blank=True, null=True)
	slika = models.ForeignKey(Slika)

	class Meta:
		verbose_name_plural = 'ocjene'

galerija/forms.py
# -*- coding: utf-8 -*-

from django import forms
from django.forms import ModelForm
from galerija.models import *
from django.utils.translation import ugettext_lazy as _


class OcjeneForm(ModelForm):
	class Meta:
		model = Ocjene
		labels = {
			'komentar': _(u'Vaš komentar'),
			'ocjena': _(u'Ocjena fotografije'),
			}
		exclude = ('slika',)

class SlikaForm(ModelForm):
	class Meta:
		model = Slika
		field = ('image', 'name')
		exclude = ('width', 'height', 'ocjena', 'thumbnail')

izbor = (
	('ocjena', 'ocjena'),
	('unos', 'unos'),
	)

class SortForm(forms.Form):
	sort = forms.ChoiceField(choices=izbor)

class ResizeForm(forms.Form):
	sirina = forms.IntegerField(label=u'Maksimalna širina', min_value=1)
	visina = forms.IntegerField(label=u'Maksimalna visina', min_value=1)

galerija/views.py
# # -*- coding: utf-8 -*-

from django.http import HttpResponseRedirect, HttpResponse, HttpResponseBadRequest
from django.shortcuts import render
from django.core.paginator import Paginator, InvalidPage, EmptyPage
from jastuk.settings import STATIC_URL, MEDIA_ROOT
from galerija.models import *
from galerija.forms import *
from django.core.urlresolvers import reverse
from PIL import Image
from os.path import join
import json



def main(request):
	slike = Slika.objects.all()
	parameters = []
	try: page = int(request.GET.get("page", '1'))
	except ValueError: page = 1
	if request.method == 'POST':
		if request.POST['action'] == 'Upload':
			uploadform = SlikaForm(request.POST, request.FILES)
			if uploadform.is_valid():
				uploadform.save()
				return HttpResponseRedirect(reverse('main'))
		elif request.POST['action'] == 'Apply':
			applyform = SortForm(request.POST)
			if applyform.is_valid():
				parameters = applyform.cleaned_data['sort']
	if page != 1 and "parameters" in request.session:
		parameters = request.session["parameters"]
	else:
		request.session["parameters"] = parameters
	if parameters == "ocjena":
		slike = Slika.objects.order_by('-ocjena')
	else:
		slike = Slika.objects.all()
	paginator = Paginator(slike, 6)
	try:
		slike = paginator.page(page)
	except (InvalidPage, EmptyPage):
		request = paginator.page(paginator.num_pages)
	uploadform = SlikaForm()
	applyform = SortForm()
	return render(request, 'galerija/list.html', {'slike': slike, 'media_url': STATIC_URL, 'uploadform': uploadform, 'applyform': applyform})


def image(request, pk):
	slika = Slika.objects.get(pk=pk)
	ocjene = Ocjene.objects.filter(slika=slika).order_by('-id')
	zadnje = ocjene[:5]
	# if request.method == 'POST':
	# 	if request.POST['action'] == 'Izracunaj':
	# 		ocjeneform = OcjeneForm(request.POST)
	# 		if ocjeneform.is_valid():
	# 			obj = ocjeneform.save(commit=False)
	# 			obj.slika = slika
	# 			obj.save()
	# 			ocjene = Ocjene.objects.filter(slika=slika).order_by('-id')
	# 			zadnje = ocjene[:5]
	# 			izracun(ocjene, slika)
	# 			data = {
	# 				'komentar': [ocjena.komentar for ocjena in ocjene],
	# 				'ocjene': [zadnji.ocjena for zadnji in zadnje],
	# 				'prosjek': slika.ocjena,
	# 				}
	# 			return HttpResponse(json.dumps(data), content_type="application/json")
	# 	if request.POST['action'] == 'Resize':
	# 		resizeform = ResizeForm(request.POST)
	# 		if resizeform.is_valid():
	# 			sirina = int(resizeform.cleaned_data['sirina'])
	# 			visina = int(resizeform.cleaned_data['visina'])
	# 			im = Image.open(join(MEDIA_ROOT, slika.image.name))
	# 			im = ImageOps.fit(im, (sirina,visina), Image.ANTIALIAS)
	# 			im.show()
	# 			if im.mode not in ('L', 'RGB'):
	# 				im = im.convert('RGB')
	# 			im.save(join(MEDIA_ROOT, "images/slikica.jpg"))
	# 			resizeform = ResizeForm()
	# 			ocjeneform = OcjeneForm()
	# 			return render(request, 'galerija/image.html', {'slika': slika, 'zadnje': zadnje, 'ocjene': ocjene, 'media_url': STATIC_URL, 'resizeform': resizeform, 'ocjeneform': ocjeneform})
	ocjeneform = OcjeneForm()
	resizeform = ResizeForm()
	return render(request, 'galerija/image.html', {'slika': slika, 'zadnje': zadnje, 'ocjene': ocjene, 'media_url': STATIC_URL, 'ocjeneform': ocjeneform, 'resizeform': resizeform})

def izracun(ocjena, slika):
	br = len(ocjena)
	brojac = suma = 0.0
	i = 0
	while (i < br):
		if (ocjena[i].slika == slika):
			if ocjena[i].ocjena != 0:
				brojac += 1
			suma = suma + ocjena[i].ocjena
		i += 1
	if suma != 0:
		slika.ocjena = suma / brojac
		slika.save(update_fields=['ocjena'])



def ajax(request, pk):
	if request.method == 'POST':
		slika = Slika.objects.get(pk=pk)
		ocjeneform = OcjeneForm(request.POST)
		if ocjeneform.is_valid():
			obj = ocjeneform.save(commit=False)
			obj.slika = slika
			obj.save()
			ocjene = Ocjene.objects.filter(slika=slika).order_by('-id')
			zadnje = ocjene[:5]
			izracun(ocjene, slika)
			data = {
				'komentar': [ocjena.komentar for ocjena in ocjene],
				'ocjene': [zadnji.ocjena for zadnji in zadnje],
				'prosjek': slika.ocjena,
				}
			if request.is_ajax():
				return HttpResponse(json.dumps(data), content_type="application/json")
			else:
				return HttpResponse('Greska!')
		else:
			if request.is_ajax():
				errors_dict = {}
				if ocjeneform.errors:
					for error in ocjeneform.errors:
						e = ocjeneform.errors[error]
						errors_dict[error] = unicode(e)
				return HttpResponseBadRequest(json.dumps(errors_dict))
			else:
				return HttpResponse('Greska2!')
	else:
		ocjeneform = OcjeneForm()
	return render(request, 'galerija/image.html', {'form': ocjeneform})

def ajax2(request, pk):
	if request.method == 'POST':
		slika = Slika.objects.get(pk=pk)
		resizeform = ResizeForm(request.POST)
		if resizeform.is_valid():
			sirina = int(resizeform.cleaned_data['sirina'])
			visina = int(resizeform.cleaned_data['visina'])
			im = Image.open(join(MEDIA_ROOT, slika.image.name))
			im = ImageOps.fit(im, (sirina,visina), Image.ANTIALIAS)
			# im.show()
			if im.mode not in ('L', 'RGB'):
				im = im.convert('RGB')
			im.save(join(MEDIA_ROOT, "images/slikica.jpg"))

			if request.is_ajax():
				return HttpResponse("images/slikica.jpg")
			else:
				return HttpResponse('Greska!')
		else:
			if request.is_ajax():
				errors_dict = {}
				if resizeform.errors:
					for error in resizeform.errors:
						e = resizeform.errors[error]
						errors_dict[error] = unicode(e)
				return HttpResponseBadRequest(json.dumps(errors_dict))
			else:
				return HttpResponse('Greska2!')
	else:
		resizeform = ResizeForm()
	return render(request, 'galerija/image.html', {'form': resizeform})

galerija/templates/galerija/ajax.html
"prosjecna ocjena": <br><br>
{{ slika.ocjena }}<br><br>
"komentari": <br><br>
[{% for ocjena in ocjene %}"{{ ocjena.komentar }}"{% if not forloop.last %},{% endif %}{% endfor %}],<br><br>
"ocjene":<br><br>
[{% for zadnji in zadnje %}"{{ zadnji.ocjena }}"{% if not forloop.last %},{% endif %}{% endfor %}]<br><br>

galerija/templates/galerija/image.html
{% extends "master.html" %}

{% block nav-global %}
<div class="main_nav">
	<div class="container">
		<div class="grid-12">

			<a class="main_nav__link" href="{% url 'main' %}">&lt; Povratak na fotografije</a>

		</div>
	</div>
</div>
{% endblock %}

{% block content %}

	<div class="container mt_20">
		<div class="grid-6 grid-tablet-8 push-tablet-2 grid-mobile-12 push-mobile-0 cf">

			<div class="solo_img">
				<img src="{{ media_url }}{{ slika.image }}" alt="{{ slika.image }}">
			</div>
			<div class="solo_img_caption">
				{{ slika.name }}, Prosječna ocjena: <strong>{{ slika.ocjena }}</strong>
			</div>
			<span class="solo_ocjene_label">Ocjene:</span>
			<ul class="solo_ocjene">
				{% for zadnji in zadnje %}
					<li>{{ zadnji.ocjena }}</li>
				{% endfor %}
			</ul>
		</div>

		<div class="grid-6 grid-tablet-12 grid-mobile-12">

			<h3 class="solo_heading">Komentari fotografije:</h3>
			<span class="solo_komentari_wrap nano">
				<ul class="solo_komentari nano-content">
					{% for ocjena in ocjene %}
						<li>{{ ocjena.komentar }}</li>
					{% endfor %}
				</ul>
			</span>

		</div>
	</div>

	<div class="tray_img mt_20">
		<div class="container cf">
			<h3>Ocjeni, komentiraj &amp; Prilagodi fotografiju:</h3>
		</div>
	</div>

	<div class="container">
		<div class="grid-4 push-2 grid-mobile-12 push-mobile-0">

			<form class="rate_photo js_ajax_form" action="{% url 'ajax' slika.pk %}" method="post" enctype="multipart/form-data">{% csrf_token %}
				{{ ocjeneform }}
				<input type="hidden" name="action" value="Izracunaj">
				<input class="js_ajax_comment_call" type="submit" value="Ocjeni fotografiju" />
			</form>

		</div>

		<div class="grid-4 push-2 grid-mobile-12 push-mobile-0">

			<span class="resize_info">
				<strong>UPUTA:</strong> Fotografija se skalira na zadanu širinu i visinu, ako je zadani omjer fotografije drugačiji od originalnog omjera fotografija će biti ogdrezana od sredine prema van. 
			</span>

			<form class="rate_photo js_ajax_resize_form" action="{% url 'ajax2' slika.pk %}" method="post" enctype="multipart/form-data">{% csrf_token %}
				{{ resizeform }}
				<input type="hidden" name="action" value="Resize">
				<input class="js_ajax_resize_call" type="submit" value="Prilagodi fotografiju" />
			</form>

		</div>
	</div>

	<div class="container mt_50"></div>

<script>
$(document).ready(function() {

    $('.js_ajax_comment_call').on('click', function(evt) {

        evt.preventDefault();

        var form = $('.js_ajax_form');

        $.ajax({
            type: form.attr('method'),
            url: form.attr('action'),
            data: form.serialize(),
            success: function (data) {

            	/* Ocjene set */
            	var itemsOcjene = [];

                for (var i=0, len=data.ocjene.length; i < len; i++) {

					itemsOcjene.push('<li>' + data.ocjene[i] + '</li>');
                }
                
                $('.solo_ocjene').html(itemsOcjene.join(''));

				/* Komentari set */
				var itemsKomentari = [];

				for (var i=0, len=data.komentar.length; i < len; i++) {

					itemsKomentari.push('<li>' + data.komentar[i] + '</li>');
				}

				$('.solo_komentari').html(itemsKomentari.join(''));

				/* Prosjek set */
				$('.solo_img_caption > strong').html( data.prosjek.toFixed(2) );

                $('.js_ajax_form')[0].reset();

            },
            error: function (textStatus, errorThrown) {
                console.log(textStatus.responseText);
            }
        });

    });

    $('.js_ajax_resize_call').on('click', function(evt) {

        evt.preventDefault();

        var form = $('.js_ajax_resize_form'),
        	data = form.serialize(),
        	visina = form.find('#id_visina').val(),
        	sirina = form.find('#id_sirina').val(),
        	visinaEkrana = $(window).height(),
        	sirinaEkrana = $(window).width(),
        	cordX = (sirinaEkrana - sirina)/2,
        	cordY = (visinaEkrana - visina)/2;

        $.ajax({
            type: form.attr('method'),
            url: form.attr('action'),
            data: data,
            success: function (data) {

            	console.log(data);            
                $('.js_ajax_resize_form')[0].reset();
                window.open('{{ STATIC_URL }}' + data,'_blank','width=' + sirina + ',height=' + visina + ',top=' + cordY + ', left=' + cordX); 

            },
            error: function (textStatus, errorThrown) {
                console.log(textStatus.responseText);
            }
        });

    });

});
</script>



{% endblock %}

galerija/templates/galerija/list.html
{% extends "master.html" %}

{% block nav-global %}
<div class="main_nav">
    <div class="container">
        <div class="grid-12">               
            
            <h1>Predajte svoju fotografiju &amp; opis:</h1>

        </div>
    </div>
</div>
{% endblock %}


{% block content %}

	<div class="container cf">
		<div class="grid-4 push-4 grid-mobile-12 push-mobile-0">
			
			<form class="upload_form" action="{% url 'main' %}" method="post" enctype="multipart/form-data">{% csrf_token %}
			    {{uploadform}}
			    <input type="hidden" name="action" value="Upload">
			    <input type="submit" value="Pošalji fotografiju &amp; opis" />
			</form>

		</div>
	</div>

	<div class="tray_img">
		<div class="container cf">
			<h3>Pregled fotografija:</h3>			
		</div>
	</div>

	<div class="container cf">
		<div class="grid-2 push-5 grid-mobile-12 push-mobile-0">

			<form class="sort_form" action="{% url 'main' %}" method="post" enctype="multipart/form-data">{% csrf_token %}
			    {{applyform}}
			    <input type="hidden" name="action" value="Apply">
			    <input type="submit" value="Sortiraj" />
			</form>

		</div>
	</div>


	<div class="container cf mt_20">

		{% for slik in slike %}
		<div class="grid-4 grid-tablet-6 grid-mobile-12">

			<figure class="figure_img">
				<a href="{% url 'image' slik.pk %}">
					<span class="img_block">
						<img src="{{ media_url }}{{ slik.thumbnail.name }}" alt="{{ slik.thumbnail.name }}">
					</span>
					<span class="caption">{{ slik.name }} ({{ slik.ocjena }})</span>
				</a>
			</figure>
			
		</div>
		{% endfor %}
	</div>

        
	<div class="container cf mt_20">

		{% if slike.object_list and slike.paginator.num_pages > 1 %}
		<div class="pagination">
			<span class="step-links">
				{% if slike.has_previous %}
					<a class="pagination__item" href= "?page={{ slike.previous_page_number }}">Prethodne &lt;&lt; </a>
				{% endif %}

				<span class="current">
					<span class="pagination__item">Page {{ slike.number }} of {{ slike.paginator.num_pages }}</span>
				</span>

				{% if slike.has_next %}
					<a class="pagination__item" href="?page={{ slike.next_page_number }}"> &gt;&gt; Sljedeće</a>
				{% endif %}
			</span>
		</div>
		{% endif %}
	</div>
{% endblock %}

jastuk/templates/master.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Slike{% endblock %}</title>
    <link rel="stylesheet" href="{{ STATIC_URL }}css/styles.css?v=20140915">
    <script src="{{ STATIC_URL }}js/libs/modernizr-2.8.2.min.js"></script>
    <script src="{{ STATIC_URL }}js/libs/jquery-1.11.1.min.js"></script>
    <script src="{{ STATIC_URL }}js/main.js?v=20140101"></script>
</head>
<body>

    <header>
        {% block nav-global %}{% endblock %}
    </header>
    

    <main>
        {% block content %}{% endblock %}
    </main>

</body>
</html>